/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    'invitation-parties': InvitationParty;
    guests: Guest;
    tags: Tag;
    tables: Table;
    'menu-courses': MenuCourse;
    'menu-options': MenuOption;
    'guest-meal-selections': GuestMealSelection;
    'photo-groups': PhotoGroup;
    'itinerary-items': ItineraryItem;
    'wedding-contacts': WeddingContact;
    media: Media;
    notifications: Notification;
    'audit-events': AuditEvent;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    'invitation-parties': InvitationPartiesSelect<false> | InvitationPartiesSelect<true>;
    guests: GuestsSelect<false> | GuestsSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    tables: TablesSelect<false> | TablesSelect<true>;
    'menu-courses': MenuCoursesSelect<false> | MenuCoursesSelect<true>;
    'menu-options': MenuOptionsSelect<false> | MenuOptionsSelect<true>;
    'guest-meal-selections': GuestMealSelectionsSelect<false> | GuestMealSelectionsSelect<true>;
    'photo-groups': PhotoGroupsSelect<false> | PhotoGroupsSelect<true>;
    'itinerary-items': ItineraryItemsSelect<false> | ItineraryItemsSelect<true>;
    'wedding-contacts': WeddingContactsSelect<false> | WeddingContactsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    'audit-events': AuditEventsSelect<false> | AuditEventsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'wedding-settings': WeddingSetting;
    'photo-queue-state': PhotoQueueState;
  };
  globalsSelect: {
    'wedding-settings': WeddingSettingsSelect<false> | WeddingSettingsSelect<true>;
    'photo-queue-state': PhotoQueueStateSelect<false> | PhotoQueueStateSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Admins manage team access. Viewers have read-only access.
   */
  role: 'admin' | 'organiser' | 'viewer';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Households and groups invited together.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invitation-parties".
 */
export interface InvitationParty {
  id: number;
  /**
   * How this group is addressed, e.g. “The Kamali Family”.
   */
  displayName: string;
  tokenHash?: string | null;
  /**
   * Incremented on rotation so old links stop working.
   */
  tokenVersion?: number | null;
  /**
   * Derived from the guests’ individual responses.
   */
  status: 'pending' | 'partial' | 'complete';
  /**
   * How many extra guests this party may bring.
   */
  plusOnesAllowed?: number | null;
  contactEmail?: string | null;
  contactPhone?: string | null;
  /**
   * Left by the party when they responded.
   */
  messageToCouple?: string | null;
  /**
   * Only ever visible to organisers.
   */
  internalNotes?: string | null;
  /**
   * When the invitation link was shared.
   */
  invitedAt?: string | null;
  respondedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Individual guests. Every guest belongs to one invitation party.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guests".
 */
export interface Guest {
  id: number;
  firstName: string;
  lastName?: string | null;
  /**
   * The group this guest was invited with.
   */
  party: number | InvitationParty;
  rsvpStatus: 'pending' | 'attending' | 'declined';
  /**
   * Drives children’s menu eligibility and catering counts.
   */
  ageGroup: 'adult' | 'child' | 'infant';
  /**
   * A placeholder seat the inviting guest may name later.
   */
  isPlusOne?: boolean | null;
  email?: string | null;
  phone?: string | null;
  /**
   * Has this guest agreed to receive text messages? Required before any SMS is sent — a phone number on its own is not permission.
   */
  smsConsent?: boolean | null;
  /**
   * Recorded automatically when consent is given, so it can be evidenced later.
   */
  smsConsentAt?: string | null;
  dietaryRequirements?: string | null;
  /**
   * Surfaced prominently to organisers and in the caterer export.
   */
  allergies?: string | null;
  accessibilityNeeds?: string | null;
  /**
   * Empty means this guest still needs a seat.
   */
  table?: (number | null) | Table;
  tags?: (number | Tag)[] | null;
  /**
   * Never shown to guests.
   */
  internalNotes?: string | null;
  respondedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tables".
 */
export interface Table {
  id: number;
  /**
   * e.g. “Top table”, “Table 4”.
   */
  name: string;
  /**
   * Advisory. You can seat more — we will warn, not refuse.
   */
  capacity: number;
  shape: 'round' | 'rectangle' | 'head';
  order: number;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-courses".
 */
export interface MenuCourse {
  id: number;
  name: string;
  description?: string | null;
  /**
   * Lower numbers appear first.
   */
  order: number;
  /**
   * Guests must choose from this course before their reply is complete.
   */
  required?: boolean | null;
  /**
   * Offered only to guests marked as children.
   */
  childrenOnly?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-options".
 */
export interface MenuOption {
  id: number;
  name: string;
  description?: string | null;
  course: number | MenuCourse;
  order: number;
  isVegetarian?: boolean | null;
  isVegan?: boolean | null;
  isGlutenFree?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * What each guest chose. Written by the RSVP form and the dashboard.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guest-meal-selections".
 */
export interface GuestMealSelection {
  id: number;
  guest: number | Guest;
  course: number | MenuCourse;
  option: number | MenuOption;
  updatedAt: string;
  createdAt: string;
}
/**
 * The photographs to take, in the order the photographer will call them.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photo-groups".
 */
export interface PhotoGroup {
  id: number;
  /**
   * What the photographer will call out, e.g. “Bride’s immediate family”. Guests see this.
   */
  name: string;
  /**
   * Optional note, e.g. “on the terrace steps”. Guests see this.
   */
  description?: string | null;
  /**
   * Roughly how long this photo takes. Used to tell guests when to start heading over.
   */
  estimatedMinutes?: number | null;
  /**
   * Lower numbers are photographed first.
   */
  order: number;
  /**
   * Managed by the wedding-day controller. You should not need to set this.
   */
  status: 'queued' | 'get_ready' | 'now' | 'completed' | 'skipped';
  /**
   * Who needs to be in this photograph.
   */
  members?: (number | Guest)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The order of the day.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "itinerary-items".
 */
export interface ItineraryItem {
  id: number;
  title: string;
  /**
   * Lower numbers appear first.
   */
  order: number;
  startTime?: string | null;
  endTime?: string | null;
  location?: string | null;
  description?: string | null;
  /**
   * Internal items are for your own planning and are never shown to guests.
   */
  visibility: 'public' | 'guests' | 'internal';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wedding-contacts".
 */
export interface WeddingContact {
  id: number;
  name: string;
  /**
   * e.g. Best Man, Maid of Honour, Wedding Coordinator.
   */
  role?: string | null;
  order: number;
  phone?: string | null;
  /**
   * Include the country code.
   */
  whatsapp?: string | null;
  email?: string | null;
  /**
   * Off by default — turn on only for people happy to be contacted.
   */
  visibleToGuests?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describes the image for screen readers. Required for accessibility.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Delivery record for email and SMS. Written by the app, never by hand.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  guest: number | Guest;
  /**
   * Makes a repeat send impossible. The uniqueness is enforced by the database, not by a check in code.
   */
  dedupeKey: string;
  channel: 'email' | 'sms';
  type: 'photo.get-ready' | 'photo.now';
  /**
   * Which service actually delivered it, e.g. resend, twilio, console.
   */
  provider?: string | null;
  status: 'queued' | 'sending' | 'sent' | 'failed';
  /**
   * Empty for SMS, which has no subject line.
   */
  subject?: string | null;
  /**
   * The message as it was sent. Rendered when the message is queued so the dispatcher never has to know what a photo group is.
   */
  body: string;
  providerMessageId?: string | null;
  attempts: number;
  lastAttemptAt?: string | null;
  /**
   * When the dispatcher will try again. Empty means it will not.
   */
  nextAttemptAt?: string | null;
  /**
   * The provider’s reason for the last failure.
   */
  error?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Append-only activity log.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-events".
 */
export interface AuditEvent {
  id: number;
  /**
   * e.g. rsvp.submitted, guest.deleted, invitation.rotated
   */
  action: string;
  actorType: 'user' | 'guest' | 'system';
  /**
   * Set when an organiser performed the action.
   */
  actorUser?: (number | null) | User;
  entityType?: string | null;
  entityId?: string | null;
  /**
   * Non-identifying context only. Never tokens or guest PII.
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Salted hash. Never a raw IP address.
   */
  ipHash?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'invitation-parties';
        value: number | InvitationParty;
      } | null)
    | ({
        relationTo: 'guests';
        value: number | Guest;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'tables';
        value: number | Table;
      } | null)
    | ({
        relationTo: 'menu-courses';
        value: number | MenuCourse;
      } | null)
    | ({
        relationTo: 'menu-options';
        value: number | MenuOption;
      } | null)
    | ({
        relationTo: 'guest-meal-selections';
        value: number | GuestMealSelection;
      } | null)
    | ({
        relationTo: 'photo-groups';
        value: number | PhotoGroup;
      } | null)
    | ({
        relationTo: 'itinerary-items';
        value: number | ItineraryItem;
      } | null)
    | ({
        relationTo: 'wedding-contacts';
        value: number | WeddingContact;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'audit-events';
        value: number | AuditEvent;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invitation-parties_select".
 */
export interface InvitationPartiesSelect<T extends boolean = true> {
  displayName?: T;
  tokenHash?: T;
  tokenVersion?: T;
  status?: T;
  plusOnesAllowed?: T;
  contactEmail?: T;
  contactPhone?: T;
  messageToCouple?: T;
  internalNotes?: T;
  invitedAt?: T;
  respondedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guests_select".
 */
export interface GuestsSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  party?: T;
  rsvpStatus?: T;
  ageGroup?: T;
  isPlusOne?: T;
  email?: T;
  phone?: T;
  smsConsent?: T;
  smsConsentAt?: T;
  dietaryRequirements?: T;
  allergies?: T;
  accessibilityNeeds?: T;
  table?: T;
  tags?: T;
  internalNotes?: T;
  respondedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tables_select".
 */
export interface TablesSelect<T extends boolean = true> {
  name?: T;
  capacity?: T;
  shape?: T;
  order?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-courses_select".
 */
export interface MenuCoursesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  order?: T;
  required?: T;
  childrenOnly?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-options_select".
 */
export interface MenuOptionsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  course?: T;
  order?: T;
  isVegetarian?: T;
  isVegan?: T;
  isGlutenFree?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guest-meal-selections_select".
 */
export interface GuestMealSelectionsSelect<T extends boolean = true> {
  guest?: T;
  course?: T;
  option?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photo-groups_select".
 */
export interface PhotoGroupsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  estimatedMinutes?: T;
  order?: T;
  status?: T;
  members?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "itinerary-items_select".
 */
export interface ItineraryItemsSelect<T extends boolean = true> {
  title?: T;
  order?: T;
  startTime?: T;
  endTime?: T;
  location?: T;
  description?: T;
  visibility?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wedding-contacts_select".
 */
export interface WeddingContactsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  order?: T;
  phone?: T;
  whatsapp?: T;
  email?: T;
  visibleToGuests?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  guest?: T;
  dedupeKey?: T;
  channel?: T;
  type?: T;
  provider?: T;
  status?: T;
  subject?: T;
  body?: T;
  providerMessageId?: T;
  attempts?: T;
  lastAttemptAt?: T;
  nextAttemptAt?: T;
  error?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-events_select".
 */
export interface AuditEventsSelect<T extends boolean = true> {
  action?: T;
  actorType?: T;
  actorUser?: T;
  entityType?: T;
  entityId?: T;
  metadata?: T;
  ipHash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * The wedding this deployment is for. Guests see most of this.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wedding-settings".
 */
export interface WeddingSetting {
  id: number;
  /**
   * First name shown on the website.
   */
  partnerOneName: string;
  partnerTwoName: string;
  /**
   * Entered in the wedding timezone below.
   */
  weddingDate: string;
  /**
   * IANA timezone, e.g. Europe/London. Guests abroad see the local ceremony time, not their own.
   */
  timezone: string;
  /**
   * After this, guests can no longer change their RSVP.
   */
  rsvpDeadline?: string | null;
  dressCode?: string | null;
  /**
   * The first thing guests read on the website.
   */
  welcomeMessage?: string | null;
  heroImage?: (number | null) | Media;
  ceremony?: {
    venueName?: string | null;
    address?: string | null;
    /**
     * Link to Google Maps or similar.
     */
    mapUrl?: string | null;
    startTime?: string | null;
    notes?: string | null;
  };
  reception?: {
    venueName?: string | null;
    address?: string | null;
    /**
     * Link to Google Maps or similar.
     */
    mapUrl?: string | null;
    startTime?: string | null;
    notes?: string | null;
  };
  travelInformation?: string | null;
  parkingInformation?: string | null;
  accommodationInformation?: string | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Turning a feature off hides it from guests and from the dashboard.
   */
  enabledFeatures?:
    | (
        | 'rsvp'
        | 'menu'
        | 'seating'
        | 'itinerary'
        | 'photoQueue'
        | 'accommodation'
        | 'travel'
        | 'faqs'
        | 'contacts'
        | 'smsNotifications'
      )[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Internal state for the live photo queue. Maintained by the app.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photo-queue-state".
 */
export interface PhotoQueueState {
  id: number;
  /**
   * Increases by one on every change to the queue.
   */
  revision: number;
  lastActionAt?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wedding-settings_select".
 */
export interface WeddingSettingsSelect<T extends boolean = true> {
  partnerOneName?: T;
  partnerTwoName?: T;
  weddingDate?: T;
  timezone?: T;
  rsvpDeadline?: T;
  dressCode?: T;
  welcomeMessage?: T;
  heroImage?: T;
  ceremony?:
    | T
    | {
        venueName?: T;
        address?: T;
        mapUrl?: T;
        startTime?: T;
        notes?: T;
      };
  reception?:
    | T
    | {
        venueName?: T;
        address?: T;
        mapUrl?: T;
        startTime?: T;
        notes?: T;
      };
  travelInformation?: T;
  parkingInformation?: T;
  accommodationInformation?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  enabledFeatures?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photo-queue-state_select".
 */
export interface PhotoQueueStateSelect<T extends boolean = true> {
  revision?: T;
  lastActionAt?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}